untitled9/apps/courses/urls.py
#coding:utf-8
from django.conf.urls import url

from .views import CourseListView, CourseDetailView, CourseInfoView, CourseCommentView, AddCommentView, VideoPlayView

urlpatterns = [
    #课程列表页
    url(r'^list/$', CourseListView.as_view(), name='list'),
    #课表详情页
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='course_detail'),
    url(r'^info/(?P<course_id>\d+)/$', CourseInfoView.as_view(), name='course_info'),
    #课程评论页
    url(r'^comment/(?P<course_id>\d+)/$', CourseCommentView.as_view(), name='course_comment'),
    #ajax添加评论
    url(r'^add_comments/$', AddCommentView.as_view(), name='add_comments'),

    #视频观看
    url(r'^video/(?P<video_id>\d+)/$', VideoPlayView.as_view(), name='video_play'),

]

untitled9/apps/organization/urls.py
# _*_ coding: utf-8 _*_

from django.conf.urls import url

from .views import OrgView
from .views import AddUserAskView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeacherView, AddFavView, TeacherListView, TeacherDetailView

__author__ = 'fzk'
__date__ = '2017/2/7 0007 10:02'


urlpatterns = [
	url(r'^list/$', OrgView.as_view(), name='org_list'),
	url(r'^add_ask/$', AddUserAskView.as_view(), name='add_ask'),
	url(r'^home/(?P<org_id>\d+)/', OrgHomeView.as_view(), name='org_home'),
	url(r'^course/(?P<org_id>\d+)/', OrgCourseView.as_view(), name='org_course'),
	url(r'^desc/(?P<org_id>\d+)/', OrgDescView.as_view(), name='org_desc'),
	url(r'^orgTeacher/(?P<org_id>\d+)/', OrgTeacherView.as_view(), name='org_teacher'),

	#机构收藏
	url(r'^add_fav/$', AddFavView.as_view(), name='add_fav'),

	#讲师列表
	url(r'^teacher/list/$', TeacherListView.as_view(), name='teacher_list'),

	url(r'^teacher/detail/(?P<teacher_id>\d+)/', TeacherDetailView.as_view(), name='teacher_detail'),
]

untitled9/apps/users/urls.py
# _*_ coding: utf-8 _*_
from django.conf.urls import url

from .views import UserInfoView, ImageUploadView, ChangePWDView, SendMailCodeView, UpdateEmailView, MyCourseView, \
	MyFavOrgView, MyFavTeacherView, MyFavCourseView, MyMessageView

__author__ = 'fzk'
__date__ = '2017/2/10 0010 10:56'

urlpatterns = [
	url(r'^center/', UserInfoView.as_view(), name='user_info'),
	url(r'^image/', ImageUploadView.as_view(), name='image_upload'),
	url(r'^change/pwd/', ChangePWDView.as_view(), name='pwd_change'),
	url(r'^sendmail_code/', SendMailCodeView.as_view(), name='sendmail_code'),
	url(r'^update_email/', UpdateEmailView.as_view(), name='update_email'),
	url(r'^my_course/', MyCourseView.as_view(), name='my_course'),
	url(r'^my_fav/org/', MyFavOrgView.as_view(), name='my_fav_org'),
	url(r'^my_fav/teacher/', MyFavTeacherView.as_view(), name='my_fav_teacher'),
	url(r'^my_fav/course/', MyFavCourseView.as_view(), name='my_fav_course'),
	url(r'^my_message/', MyMessageView.as_view(), name='my_message'),

]

untitled9/untitled9/urls.py
from django.conf.urls import url, include
import xadmin
from django.views.static import serve

from users.views import LoginView, RegisterView, ActiveUserView, ForgetView, ResetPasswordView, ModifyPWDView, LogoutView, IndexView
from untitled9.settings import MEDIA_ROOT


urlpatterns = [
    url(r'^admin/', xadmin.site.urls),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    url(r'^register', RegisterView.as_view(), name='register'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name='user_active'),
    url(r'^forget', ForgetView.as_view(), name='forget_pwd'),
    url(r'^reset/(?P<active_code>.*)/$', ResetPasswordView.as_view(), name='password_reset'),
    url(r'^modify_pwd/$', ModifyPWDView.as_view(), name='password_modify'),
    url(r'^media/(?P<path>.*)', serve, {'document_root': MEDIA_ROOT}),

    url(r'^org/', include('organization.urls', namespace='org')),

    url(r'^course/', include('courses.urls', namespace='course')),

    url('^user/', include('users.urls', namespace='user')),

    url(r'^ueditor/', include('DjangoUeditor.urls')),

]

handler404 = 'users.views.page_not_found'
handler500 = 'users.views.server_error'

untitled9/apps/courses/models.py
# coding:utf-8
from __future__ import unicode_literals
from datetime import datetime

from DjangoUeditor.models import UEditorField

from django.db import models
from organization.models import CourseOrg, Teacher


# Create your models here.


class Course(models.Model):
	course_org = models.ForeignKey(CourseOrg, verbose_name=u'所属机构', null=True, blank=True)
	name = models.CharField(max_length=50, verbose_name=u"课程名称")
	desc = models.CharField(max_length=300, verbose_name=u"课程描述")
	is_banner = models.BooleanField(default=False, verbose_name=u'广告位')
	detail = UEditorField(default='', verbose_name=u'课程详情', width=600, height=300, imagePath="course/ueditor/",
	                      filePath="course/ueditor/")
	teacher = models.ForeignKey(Teacher, verbose_name=u'讲师', null=True, blank=True)
	category = models.CharField(verbose_name=u'课程类别', max_length=20, default='后端开发')
	degree = models.CharField(choices=(('cj', u'初级'), ('zj', u'中级'), ('gj', u'高级')), max_length=5, verbose_name=u"课程难度")
	learn_times = models.IntegerField(default=0, verbose_name=u"学习时间")
	student = models.IntegerField(default=0, verbose_name=u"学习人数")
	fav_nums = models.IntegerField(default=0, verbose_name=u"收藏人数")
	youneed_knew = models.CharField(default='', max_length=200, verbose_name=u'课程须知')
	learn_about = models.CharField(default='', max_length=200, verbose_name=u'通过本课程后能学到的')
	tag = models.CharField(default='', max_length=50, verbose_name=u'课程标签')
	image = models.ImageField(upload_to="course/%Y/%m", verbose_name=u"课程首页图片", max_length=100)
	click_nums = models.IntegerField(default=0, verbose_name=u"点击次数")
	add_time = models.DateTimeField(default=datetime.now, verbose_name=u"创建时间")

	class Meta:
		verbose_name = u"课程"
		verbose_name_plural = verbose_name

	def __unicode__(self):
		return self.name

	def get_zj_nums(self):
		return self.lesson_set.all().count()

	get_zj_nums.short_description = u"章节数"

	def get_user_course(self):
		return self.usercourse_set.all()

	def get_lessons(self):
		return self.lesson_set.all()

	def get_course_resources(self):
		return self.courseresource_set.all()


class BannerCourse(Course):
	class Meta:
		verbose_name = u'轮播图'
		verbose_name_plural = verbose_name
		proxy = True


class Lesson(models.Model):
	course = models.ForeignKey(Course, verbose_name=u"课程名称")
	name = models.CharField(max_length=100, verbose_name=u"章节名称", default=u'第一章：')
	add_time = models.DateTimeField(default=datetime.now, verbose_name=u"创建时间")

	class Meta:
		verbose_name = u"章节"
		verbose_name_plural = verbose_name

	def __unicode__(self):
		return self.name

	def get_videos(self):
		return self.video_set.all()


class Video(models.Model):
	lesson = models.ForeignKey(Lesson, verbose_name=u"课程名称")
	name = models.CharField(max_length=100, verbose_name=u"视频名称", default=u'第一节：')
	url = models.CharField(max_length=100, default='', verbose_name=u"视频链接")
	learn_times = models.IntegerField(default=0, verbose_name=u"视频时长")
	add_time = models.DateTimeField(default=datetime.now, verbose_name=u"创建时间")

	class Meta:
		verbose_name = u"视频"
		verbose_name_plural = verbose_name

	def __unicode__(self):
		return self.name


class CourseResource(models.Model):
	course = models.ForeignKey(Course, verbose_name=u"课程名称")
	name = models.CharField(max_length=100, verbose_name=u"课件名称")
	download = models.FileField(upload_to="course/resource/%Y%m", verbose_name=u"资源文件", max_length=100)
	add_time = models.DateTimeField(default=datetime.now, verbose_name=u"创建时间")

	class Meta:
		verbose_name = u"资源文件"
		verbose_name_plural = verbose_name

	def __unicode__(self):
		return self.name

untitled9/extra_apps/xadmin/views/base.py
import sys
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.utils.encoding import force_unicode, force_text
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_unicode, smart_unicode, smart_str
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, basestring) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_unicode(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        for r in remove:
            for k in p.keys():
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        for r in remove:
            for k in p.keys():
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

    def init_request(self, *args, **kwargs):
        pass

    def init_plugin(self, *args, **kwargs):
        plugins = []
        for p in self.base_plugins:
            p.request = self.request

untitled9/templates/course-video.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}公开课视频信息 - 慕学在线网{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aui.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
{% endblock %}

{% block custom_bread %}
<section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="/">首页</a>></li>
                <li><a href="{% url 'course:list' %}">公开课程</a>></li>
				<li><a href="{% url 'course:course_detail' course.id %}">课程详情</a>></li>
                <li>课程章节</li>
			</ul>
		</div>
	</div>
</section>
{% endblock %}

{% block content %}
<div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">&nbsp;{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.learn_times }}</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.student }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"  href="{% url 'course:course_info' course.id %}"><span>章节</span></a></li>
                        <li><a id="commentOn" class="" href="{% url 'course:course_comment' course.id %}"><span>评论</span></a></li>
                    </ul>
                </div>
                <div id="notice" class="clearfix">
                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">相关文档已上传</a> </div>
                </div>
                {% for lesson in lessons %}
                    <div class="mod-chapters">
                                        <div class="chapter chapter-active" >
                                            <h3>
                                                <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                                            </h3>
                                                        <ul class="video">
                                                            {% for video in lesson.get_videos %}
                                                            <li>

                                                                <a target="_blank" href='{% url 'course:video_play' video.id %}' class="J-media-item studyvideo">{{ video.name }}  { {{ video.learn_times }} }
                                                                    <i class="study-state"></i>
                                                                </a>

                                                            </li>
                                                            {% endfor %}
                                                        </ul>


                                        </div>
                                    </div>
                {% endfor %}

            </div>
            <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                        {% for resource in resources %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ resource.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ resource.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                        {% endfor %}
                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
        </span>
                            <span class="job">{{ course.teacher.work_position}}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.youneed_knew }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.learn_about }}</dd>
                            </dl>
                        </div>
                    </div>


                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">学过该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">
                                {% for relate_course in relate_courses %}
                                    <li class="curr">
                                        <a href="{% url 'course:course_detail' relate_course.id %}" target="_blank">
                                            <img src="{{ MEDIA_URL }}{{ relate_course.image }}" alt="{{ relate_course.name }}">
                                            <span class="name autowrap">{{ relate_course.name }}</span>
                                        </a>
                                    </li>
                                {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>    </div>
        </div>
        <div class="clear"></div>

    </div>

</div>
</div>
{% endblock %}

untitled9/templates/email_send_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>邮件已发送，请查收</p>
</body>
</html>

untitled9/templates/org-detail-homepage.html
{% extends 'org_base.html' %}

{% block title %}机构首页 - 慕学网{% endblock %}
{% block page_path %}机构首页{% endblock %}
{% block right_form %}
<div class="right companycenter layout grouping" >
		<div class="head">
			<h1>全部课程</h1>
			<a class="green fr more" href="{% url 'org:org_course' course_org.id %}">查看更多</a>
		</div>
    {% for course in all_courses %}
        <div class="brief group_list">
                <div class="module1_5 box">
                    <a href="{% url 'course:course_detail' course.id %}"><img width="214" src="{{ MEDIA_URL }}{{ course.image }}"/></a>
                    <div class="des">
                        <a href="{% url 'course:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                        <span class="fl">课时：<i class="key">{{ course.learn_times }}</i></span>
                        <span class="fr">参加人数：{{ course.student }}</span>
                    </div>
                    <div class="bottom">
                        <span class="fl">{{ course.course_org.name }}</span>
                         <span class="star fr  notlogin
                            " data-favid="13"  data-fav-type="4">
                            {{ course.fav_nums }}
                        </span>
                    </div>
                </div>
		</div>
    {% endfor %}
</div>
<div class="right companycenter layout" >
    <div class="head">
        <h1>机构教师</h1>
        <a class="green fr more" href="{% url 'org:teacher_list' %}">查看更多  >  </a>
    </div>
    <div class="diarys">
        {% for teach in all_teachers %}
        <div class="module5 share company-diary-box" style="padding:10px 0;">
            <div class="left">
                <img class="pic" src="{{ MEDIA_URL }}{{ teach.image }}"/>
                <p>昵称：{{ teach.name }}</p>
            </div>
            <div class="right">
                <div class="top">
                    {% for course in all_courses %}
                        <div class="fl">
                        <a href=""><h1>{{ course.name }}</h1></a>
                        <span>发表于：{{ course.add_time }}</span>
                    </div>
                    {% endfor %}
                </div>
                <div class="middle" style="border-bottom:0;">课程介绍</div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="right companycenter layout" >
    <div class="head">
        <h1>机构介绍</h1>
        <a class="green fr more" href="{% url 'org:org_desc' course_org.id %}">查看更多</a>
    </div>
    <div class="cont">&nbsp; &nbsp; {{ course_org.desc }}<p>&nbsp; &nbsp;</p><h1 class="ue_t" label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;"><span style="color:#c0504d;">[键入文档标题]</span></h1><p style="text-align:center;"><strong class="ue_t">[键入文档副标题]</strong></p><h3><span class="ue_t" style="font-family:幼圆">[标题 1]</span></h3><p class="ue_t" style="text-indent:2em;">对于“插入”选项卡上的库，在设计时都充分考虑了其中的项与文档整体外观的协调性。 您可以使用这些库来插入表格、页眉、页脚、列表、封面以及其他文档构建基块。 您创建的图片、图表或关系图也将与当前的文档外观协调一致。</p><p class="ue_t" style="text-indent:2em;"><img src="{{ MEDIA_URL }}{{ course_org.image }}" title="" alt="57aa86a0000145c512000460.jpg"/> </p><h3><span class="ue_t" style="font-family:幼圆">[标题 2]</span></h3><p><img src="http://api.map.baidu.com/staticimage?center=116.410899,39.863624&zoom=11&width=530&height=340&markers=116.404,39.915" width="530" height="340"/> </p><p class="ue_t" style="text-indent:2em;">在“开始”选项卡上，通过从快速样式库中为所选文本选择一种外观，您可以方便地更改文档中所选文本的格式。 您还可以使用“开始”选项卡上的其他控件来直接设置文本格式。大多数控件都允许您选择是使用当前主题外观，还是使用某种直接指定的格式。</p><h3><span class="ue_t" style="font-family:幼圆">[标题 3]</span></h3><p>2016-12-10</p><p class="ue_t">对于“插入”选项卡上的库，在设计时都充分考虑了其中的项与文档整体外观的协调性。 您可以使用这些库来插入表格、页眉、页脚、列表、封面以及其他文档构建基块。 您创建的图片、图表或关系图也将与当前的文档外观协调一致。</p><p class="ue_t"><br/> </p><p><br/></p><p><br/></p><a href="/company/desc/22/"><span class="green">[查看更多]</span></a></div>
</div>
{% endblock %}